site_name: Pipelex Docs
site_url: https://docs.pipelex.com/
site_description: "Official documentation for Pipelex, a framework and language for building deterministic, repeatable AI workflows and knowledge pipelines."
docs_dir: docs
repo_url: "https://github.com/Pipelex/pipelex"
repo_name: "Pipelex on GitHub"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, MANIFESTO.md, LICENSE]

theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/pipelex-favicon-32.png
  logo: https://pipelex-web.s3.amazonaws.com/logo/Pipelex-logo-wot-mono-560x176.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
  - scheme: default          # light
    primary: teal
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate            # dark
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

copyright: "Â© 2025 Evotis S.A.S. <br/>Pipelex is a trademark of Evotis S.A.S."

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pipelex/pipelex
      name: Pipelex on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pipelex/
      name: pipelex on PyPI
    - icon: fontawesome/brands/twitter
      link: https://x.com/PipelexAI
      name: Pipelex on X
    - icon: fontawesome/brands/discord
      link: https://go.pipelex.com/discord
      name: Pipelex on Discord
  generator: false

plugins:
  - search
  - meta-manager
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - meta
  - sane_lists
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home:
    - Welcome: index.md
    - Writing Workflows: pages/writing-workflows/index.md
    - Setup:
      - Configure AI Providers: pages/setup/configure-ai-providers.md
      - Project Organization: pages/setup/project-organization.md
      - Telemetry: pages/setup/telemetry.md
    - Understand Pipelex:
      - The Knowledge Pipeline Manifesto: manifesto.md
      - The Pipelex Paradigm: pages/pipelex-paradigm-for-repeatable-ai-workflows/index.md
    - Cookbook Examples:
      - Overview: pages/cookbook-examples/index.md
      - Hello World: pages/cookbook-examples/hello-world.md
      - Document Processing:
        - Simple OCR: pages/cookbook-examples/simple-ocr.md
        - Generic Document Extraction: pages/cookbook-examples/extract-generic.md
        - Invoice Extractor: pages/cookbook-examples/invoice-extractor.md
        - Proof of Purchase Extraction: pages/cookbook-examples/extract-proof-of-purchase.md
      - Graphical Extraction:
        - Gantt Chart Extraction: pages/cookbook-examples/extract-gantt.md
        - Table Extraction from Image: pages/cookbook-examples/extract-table.md
        - DPE Extraction: pages/cookbook-examples/extract-dpe.md
      - Text Generation:
        - Screenplay Generator (wip): pages/cookbook-examples/write-screenplay.md
        - Tweet Optimizer (wip): pages/cookbook-examples/write-tweet.md
    - Build Reliable AI Workflows:
      - Kick off a Pipeline Project: pages/build-reliable-ai-workflows-with-pipelex/kick-off-a-pipelex-workflow-project.md
      - Define Your Concepts: pages/build-reliable-ai-workflows-with-pipelex/define_your_concepts.md
      - Structuring Concepts: pages/build-reliable-ai-workflows-with-pipelex/structuring-concepts.md
      - Design and Run Pipelines: pages/build-reliable-ai-workflows-with-pipelex/design_and_run_pipelines.md
      - Executing Pipelines with Inputs: pages/build-reliable-ai-workflows-with-pipelex/executing-pipelines-with-inputs.md
      - Understanding Multiplicity: pages/build-reliable-ai-workflows-with-pipelex/understanding-multiplicity.md
      - Pipeline Creation: pages/build-reliable-ai-workflows-with-pipelex/pipeline-creation.md
      - Pipe Operators:
        - Overview: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/index.md
        - PipeLLM: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeLLM.md
        - PipeExtract: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeExtract.md
        - PipeImgGen: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeImgGen.md
        - PipeCompose: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeCompose.md
        - PipeFunc: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeFunc.md
      - Pipe Controllers:
        - Overview: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/index.md
        - PipeSequence: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeSequence.md
        - PipeParallel: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeParallel.md
        - PipeBatch: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeBatch.md
        - PipeCondition: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeCondition.md
      - Optimize Cost & Quality: pages/build-reliable-ai-workflows-with-pipelex/configure-ai-llm-to-optimize-workflows.md
      - LLM Structured Generation: pages/build-reliable-ai-workflows-with-pipelex/llm-structured-generation-config.md
      - LLM Prompting Style: pages/build-reliable-ai-workflows-with-pipelex/adapt-to-llm-prompting-style-openai-anthropic-mistral.md
      - LLM Providers & Models: pages/configuration/config-technical/inference-backend-config.md
  - Observer:
    - Data Extraction: pages/observer/data-extraction.md
  - API Reference:
    - API Guide: pages/api/index.md
  - n8n Node: https://pipelex.github.io/n8n-nodes-pipelex/
  - Configuration:
    - Overview: pages/configuration/index.md
    - Pipeline Validation Configuration:
      - Dry Run: pages/configuration/config-pipeline-validation/dry-run-config.md
      - Static Validation: pages/configuration/config-pipeline-validation/static-validation-config.md
    - Practical Configuration:
      - Logging: pages/configuration/config-practical/logging-config.md
      - Pipe Run: pages/configuration/config-practical/pipe-run-config.md
      - Reporting: pages/configuration/config-practical/reporting-config.md
      - Telemetry: pages/configuration/config-practical/telemetry-config.md
      - Tracker: pages/configuration/config-practical/tracker-config.md
    - Technical Configuration:
      - AWS: pages/configuration/config-technical/aws-config.md
      - Cogt: pages/configuration/config-technical/cogt-config.md
      - Inference Backend: pages/configuration/config-technical/inference-backend-config.md
      - Library: pages/configuration/config-technical/library-config.md
      - Feature: pages/configuration/config-advanced/feature-config.md
  - Development:
    - Changelog: changelog.md
    - Tools:
      - CLI: pages/tools/cli.md
      - Kit Commands: pages/tools/kit.md
      - Pipe Builder: pages/tools/pipe-builder.md
      - Logging: pages/tools/logging.md
    - Advanced Customizations:
      - Overview: pages/advanced-customization/index.md
      - Secrets Provider: pages/advanced-customization/secrets-provider-injection.md
      - Reporting Delegate: pages/advanced-customization/reporting-delegate-injection.md
      - Pipeline Tracker: pages/advanced-customization/pipeline-tracker-injection.md
      - Storage Provider: pages/advanced-customization/storage-provider-injection.md
      - Template Provider: pages/advanced-customization/template-provider-injection.md
      - Observer Provider: pages/advanced-customization/observer-provider-injection.md
      - Content Generator: pages/advanced-customization/content-generator-injection.md
      - Pipe Router: pages/advanced-customization/pipe-router-injection.md
    - License: license.md
    - Contributing: contributing.md
    - Code of Conduct: CODE_OF_CONDUCT.md

extra_css:
  - stylesheets/mermaid.css
  - stylesheets/general.css
  