name: Tests check

on:
  pull_request:

jobs:
  matrix-test:
    name: Tests check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    permissions:
      contents: read
      id-token: write
    env:
      VIRTUAL_ENV: ${{ github.workspace }}/.venv
      ENV: dev
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check UV installation
        run: make check-uv

      - name: Verify UV installation
        run: uv --version

      - name: Install dependencies
        run: PYTHON_VERSION=${{ matrix.python-version }} make install

      - name: Boot test
        run: make tp TEST=TestFundamentals

      - name: Run tests
        run: make gha-tests
